runtime: php74

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:2bo9sE37KebouzYkvSAiY5pgUL5wy5bxMefxOoH3VWM=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.
  DB_DATABASE: nozom_ecommerce
  DB_USERNAME: root
  DB_PASSWORD: asd@asd@
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/YOUR_CONNECTION_NAME"
  ## for PostgreSQL, use DB_HOST:
  # DB_HOST: "/cloudsql/YOUR_CONNECTION_NAME"
